// These are types of actions
export const GET_COURSES = 'GET_COURSES';
export const SELECT_COURSE = "SELECT_COURSE";

export const FETCH_COURSE = 'FETCH_COURSE';
export const SET_COURSE = 'SET_COURSE';
export const FETCH_FAILURE = 'FETCH_FAILURE';

//=====================CONSTANTS FOR SIGN UP/LOG IN FORM ACTIONS ==========================
export const SET_SIGN_UP_USERNAME = 'SET_SIGN_UP_USERNAME';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_SIGN_UP_PASSWORD = 'SET_SIGN_UP_PASSWORD';
export const SET_CONFIRM_PASSWORD = 'SET_CONFIRM_PASSWORD';
export const SET_SIGN_UP_RESPONSE = 'SET_SIGN_UP_RESPONSE';
export const VALIDATE_SIGN_UP_USERNAME = 'VALIDATE_SIGN_UP_USERNAME';
export const VALIDATE_EMAIL = 'VALIDATE_EMAIL';
export const VALIDATE_SIGN_UP_PASSWORD = 'VALIDATE_SIGN_UP_PASSWORD';
export const VALIDATE_CONFIRM_PASSWORD = 'VALIDATE_CONFIRM_PASSWORD';
export const SUBMIT_SIGNUP_FORM = 'SUBMIT_SIGNUP_FORM';


export const VALIDATE_LOG_IN_USERNAME = 'VALIDATE_LOG_IN_USERNAME';
export const VALIDATE_LOG_IN_PASSWORD = 'VALIDATE_LOG_IN_PASSWORD';
export const SET_LOG_IN_USERNAME = 'SET_LOG_IN_USERNAME';
export const SET_LOG_IN_PASSWORD = 'SET_LOG_IN_PASSWORD';
export const SUBMIT_LOG_IN_FORM = 'SUBMIT_LOG_IN_FORM';
export const SET_ENTIRE_LOG_IN_FORM_STATE = 'SET_ENTIRE_LOG_IN_FORM_STATE';
export const RESET_LOG_IN_FORM = 'RESET_LOG_IN_FORM';
export const SET_LOG_IN_RESPONSE = 'SET_LOG_IN_RESPONSE';
export const REQUEST_ACTIVE_ACCOUNT = 'REQUEST_ACTIVE_ACCOUNT';
export const RESET_RESPONSE_DATA = 'RESET_RESPONSE_DATA';

export const SET_ENTIRE_SIGN_UP_FORM_STATE = 'SET_ENTIRE_SIGN_UP_FORM_STATE';
export const REQUEST_RESET_SIGN_UP_FORM = 'REQUEST_RESET_SIGN_UP_FORM';
export const RESET_SIGN_UP_FORM = 'RESET_SIGN_UP_FORM';

// ===================CONSTANT FOR VERIFY CODE FORM ACTIONS ==========================
export const VALIDATE_CODE =  'VALIDATE_CODE';
export const SET_CODE = 'SET_CODE';
export const SET_VERIFY_CODE_RESPONSE = 'SET_VERIFY_CODE_RESPONSE';
export const SUBMIT_VERIFY_CODE_FORM = 'SUBMIT_VERIFY_CODE_FORM';
export const SET_ENTIRE_VERIFY_CODE_FORM_STATE = 'SET_ENTIRE_VERIFY_CODE_FORM_STATE';
export const REQUEST_RESET_VERIFY_CODE_FORM = 'REQUEST_RESET_VERIFY_CODE_FORM';
export const RESET_VERIFY_CODE_FORM = 'RESET_VERIFY_CODE_FORM';

// ========================CONSTANTS FOR SEARCH COURSE ACTIONS ===============================
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const FETCH_SEARCH_COURSE = 'FETCH_SEARCH_COURSE';
export const SET_SEARCH_COURSE_RESULT='SET_SEARCH_COURSE_RESULT';
export const RESET_SEARCH_FORM= 'RESET_SEARCH_FORM';

// ===========================================================================================
// hotCourses action
export const FETCH_HOT_COURSES = 'FETCH_HOT_COURSES';
export const SET_HOT_COURSES = 'SET_HOT_COURSES';
export const FETCH_HOT_COURSES_FAILURE = 'FETCH_HOT_COURSES_FAILURE';

// coursesOfLecturer
export const FETCH_LECTURER_COURSES = 'FETCH_LECTURER_COURSES';
export const SET_LECTURER_COURSES = 'SET_LECTURER_COURSES';
export const FETCH_LECTURER_COURSES_FAILURE = 'FETCH_LECTURER_COURSES_FAILURE';
